### PR TITLE
Created note listing UI - Fixed previous reverting issues

### LINKED ISSUE #3: Create note listing page UI

### PR DESCRIPTION
**Pull request by alan-thomas-shaji**
Fixes #3 
Reverting this after a minor issue in branching

### CODE REVIEW

File: app/javascript/src/App.jsx [hunk 1]
```diff
@@ -1,5 +1,7 @@
 import React from "react";
 
+import "src/utils/dayjs"; //eslint-disable-line
```
Comment (yedhink) [inline app/javascript/src/App.jsx:3]: Go through https://academy.bigbinary.com/learn-react/pages/miscellaneous-tips#:~:text=How%20to%20extend%20day.js%3F very well and make necessary changes.

The point of writing and documenting standards in the React Best Practices book is to ensure that we avoid redundant review comments like the one I am giving right now.

If you don't agree with what's mentioned in the book, then it's totally fine and it's acceptable to keep this change. But you ought to initiate a discussion and make your strong points against the content from the book. If there's a need to update the content in the book then we can do that.

If you feel the content in the book makes sense and if you are not following those standards in your code, then that's not acceptable. I understand that folks miss things out. Thus the self-review process. Read: https://handbook.neetokb.com/articles/git-and-github-essentials#self-review-process

File: app/javascript/src/components/Common/Sidebar/index.jsx [hunk 2]
```diff
@@ -48,17 +49,19 @@ const Sidebar = () => {
...
         subdomain: "bigbinary.com",
       }}
       profileInfo={{
         name: `${user.first_name} ${user.last_name}`,
-        imageUrl: user.profile_image_path,
+        imageUrl: "https://i.pravatar.cc/300",
         email: user.email,
         bottomLinks,
       }}
+      onCollapse={() => setIsSidebarCollapsed(!isSidebarCollapsed)}
```
Comment (yedhink) [inline app/javascript/src/components/Common/Sidebar/index.jsx:64]: https://academy.bigbinary.com/learn-react/pages/know-when-to-use-previous-state-for-state-update

File: app/javascript/src/components/Dashboard/Notes/Menu.jsx [hunk 3]
```diff
@@ -0,0 +1,71 @@
...
+      <MenuBar showMenu={showMenu} title="Notes">
+        <MenuBar.Block count={80} label="All" />
+        <MenuBar.Block count={80} label="Users" />
+        <MenuBar.Block count={60} label="Leads" />
+        <MenuBar.Block count={60} label="Visitors" />
+        <MenuBar.SubTitle
+          iconProps={[
+            {
+              icon: Search,
+              onClick: previousValue => setIsSearchCollapsed(!previousValue),
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Menu.jsx:21]: You haven't understood what you are actually doing. Nor have you don't a self-review. This expressions is invalid.

Read: https://academy.bigbinary.com/learn-react/pages/know-when-to-use-previous-state-for-state-update

File: app/javascript/src/components/Dashboard/Notes/Note.jsx [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+
+const Note = ({ note }) => (
+  <div className="mb-3 w-full  border border-gray-300 bg-white p-4 shadow-md  dark:border-gray-700 dark:bg-gray-800 ">
+    <div className="flex justify-between">
+      <Typography style="h4" weight="bold">
+        {note.title}
+      </Typography>
+      <Dropdown buttonStyle="text" icon={MenuVertical}>
+        <li>Edit</li>
+        <li>Delete</li>
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Note.jsx:16]: Make sure to carefully go through the review comments I have put up in the Slack thread.

File: app/javascript/src/components/Dashboard/Notes/Note.jsx [hunk 5]
```diff
@@ -0,0 +1,51 @@
...
+      </Dropdown>
+    </div>
+    <div className="mb-2">
+      <Typography className="--neeto-ui-gray-600">
+        {note.description}
+      </Typography>
+    </div>
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Note.jsx:23]: Why do we need this div here? What's the issue with keeping this classname within `Typography`?

File: app/javascript/src/components/Dashboard/Notes/Note.jsx [hunk 6]
```diff
@@ -0,0 +1,51 @@
...
+      <Typography style="h4" weight="bold">
+        {note.title}
+      </Typography>
+      <Dropdown buttonStyle="text" icon={MenuVertical}>
+        <li>Edit</li>
+        <li>Delete</li>
+      </Dropdown>
+    </div>
+    <div className="mb-2">
+      <Typography className="--neeto-ui-gray-600">
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Note.jsx:20]: Had you done a self-review from your end? If yes, please put up a screenshot and show me this exact color being rendered in the UI.

File: app/javascript/src/components/Dashboard/Notes/Note.jsx [hunk 7]
```diff
@@ -0,0 +1,51 @@
...
+        {note.description}
+      </Typography>
+    </div>
+    <hr />
+    <div className="flex justify-between">
+      <div className="mt-3">
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Note.jsx:26]: Do we need this div?

File: app/javascript/src/components/Dashboard/Notes/Note.jsx [hunk 8]
```diff
@@ -0,0 +1,51 @@
...
+        <Tag
+          className="neeto-ui-bg-gray-200"
+          label="Getting Started"
+          size="small"
+        />
+      </div>
+      <div className="mt-3 flex items-center space-x-1">
+        <Clock size={15} />
+        <Tooltip content={createdAtFormat(note.createdAt)} position="bottom">
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Note.jsx:35]: No need to couple this util function with the `createdAt` entity. Coupling over here cripples the reusability of this util function. Keep it something more business friendly like `formatDateToLongFormat`

File: app/javascript/src/components/Dashboard/Notes/Note.jsx [hunk 9]
```diff
@@ -0,0 +1,51 @@
...
+          <Typography style="body3">
+            Created {createdAgoFormat(note.createdAt)}{" "}
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/Note.jsx:37]: Refer prev comment.

Also use string interpolation. Rendering empty spaces in JSX like you've done right now is an anti-pattern.

File: app/javascript/src/components/Dashboard/Notes/index.jsx [hunk 10]
```diff
@@ -1,107 +1,53 @@
...
+import { Button } from "neetoui";
+import { Container, Header } from "neetoui/layouts";
 
-import notesApi from "apis/notes";
 import EmptyState from "components/Common/EmptyState";
 
-import DeleteAlert from "./DeleteAlert";
-import NewNotePane from "./Pane/Create";
-import Table from "./Table";
+import { NOTES_CARD_DATA as notes_content } from "./constants";
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/index.jsx:9]: You are not going through the React Best Practices very well. I want you to be extra careful and go through the materials very well.

Read: https://academy.bigbinary.com/learn-react/pages/naming-conventions-in-react#:~:text=Use%20upper%20snake%20case%20in%20constant%20name

File: app/javascript/src/components/Dashboard/Notes/index.jsx [hunk 11]
```diff
@@ -1,107 +1,53 @@
...
+          }
+          searchProps={{
+            value: searchTerm,
+            placeholder: "Search Name, Email, Phone Number, Etc.",
+            onChange: e => setSearchTerm(e.target.value),
+          }}
         />
-      )}
-    </Container>
+        {notes_content.length ? (
```
Comment (yedhink) [inline app/javascript/src/components/Dashboard/Notes/index.jsx:38]: 1) Why are you using snake_case in React? Read: https://academy.bigbinary.com/learn-react/pages/naming-conventions-in-react

File: app/javascript/src/utils/dateFormats.js [hunk 12]
```diff
@@ -0,0 +1,7 @@
+import dayjs from "dayjs";
```
Comment (yedhink) [inline app/javascript/src/utils/dateFormats.js:1]: https://academy.bigbinary.com/learn-react/pages/structuring-code#:~:text=Keep%20the%20files%20in%20closest%20scope

Also the filename `dateFormats` is not right. It sounds as if it stores different date format constants. Whereas here we are `formatting` something into a different format.

**Review by yedhink — COMMENTED** [review]
@alan-thomas-shaji

File: app/javascript/src/App.jsx (hunk 1 above)
Comment (alan-thomas-shaji) [reply app/javascript/src/App.jsx:3]: What led me to keep this in utils instead of lib was the thought that this would clean the overall directory structure since there wasn't anything else in the lib sub-directory. I will look into that further.

Comment (yedhink) [reply app/javascript/src/App.jsx:3]: Read: https://www.bigbinary.com/books/learn-rubyonrails-book/more-rails-content-and-goodies#the-lib-folder-and-its-use-cases

Comment (yedhink) [reply app/javascript/src/App.jsx:3]: >What led me to keep this in utils instead of lib was the thought that this would clean the overall directory structure since there wasn't anything else in the lib sub-directory

Your thought process is not right. `utils` is supposed to hold utility functions. You are adding any utility functions here. You are initializing or extending a 3rd party library.

File: app/javascript/src/components/Dashboard/Notes/index.jsx (hunk 11 above)
Comment (alan-thomas-shaji) [reply app/javascript/src/components/Dashboard/Notes/index.jsx:38]: Sorry for that, I will change it

File: app/javascript/src/components/Dashboard/Notes/index.jsx (hunk 10 above)
Comment (alan-thomas-shaji) [reply app/javascript/src/components/Dashboard/Notes/index.jsx:9]: I will quickly go through best practices again.

File: app/javascript/src/components/Dashboard/Notes/Note.jsx (hunk 8 above)
Comment (alan-thomas-shaji) [reply app/javascript/src/components/Dashboard/Notes/Note.jsx:35]: Noted, will change that.

File: app/javascript/src/App.jsx (hunk 1 above)
Comment (alan-thomas-shaji) [reply app/javascript/src/App.jsx:3]: I understood the issue and changed it. I also renamed the date format functions as wasCreatedAtFormat and wasCreatedAgoFormat respectively to make the name more obvious. I hope this naming convention was okay.

Comment (yedhink) [reply app/javascript/src/App.jsx:3]: No need to couple `createdAt` with the util functions. Keep the util functions generic.

Something like `formatWithDayAndDate`, `formatWithShortDate` or `formatWithLongDate` etc are examples of generic names.
